---
title: "Applied Data Science:  Midterm Project"
author: ""
date: ""
output:
  prettydoc::html_pretty:
  theme: cayman
highlight: github
---

```{r setup, include=FALSE}
set.seed(72)
knitr::opts_chunk$set(echo = TRUE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55))
```

```{r libraries, echo = FALSE}
library(data.table)
library(DT)
```

```{r source_files}

```

```{r functions}

```

```{r constants}
n.values <- c(500, 1000, 2000)
iterations <- 3
```

```{r load_data}

```

```{r clean_data}

```

```{r generate_samples}

```

## Introduction


### Model 1:  


```{r code_model1_development, eval = TRUE}
model_glm <- function(train_data, test_data = test.data){
  t1 <- Sys.time()
  glm.fit <- glmnet(train_data$x,y = as.factor(train_data$y), family = "multinomial")
  predglm <- predict(object = glm.fit, newx=test_data$x,type="class")
  t2 <- Sys.time()
  A <- round(length(train_data$y) / 60000, 4)
  B <- round(min(1, as.numeric(t2 - t1) / 60), 4)
  C <- round(mean(predglm[,ncol(predglm)] != test_data$y), 4)
  
  return(list(A = A, B = B, C = C, model.name = "glm"))
}
```

```{r load_model1}
iteration_func(model = model_glm, train_data = train_data_sample)
```

### Model 2:  


```{r code_model2_development, eval = TRUE}
model_ridge <- function(train_data, test_data = test.data){
  t1 <- Sys.time()
  ridge <- glmnet(x = train_data$x, as.factor(train_data$y), alpha = 0, family = "multinomial")
  predridge <- predict(object = ridge, newx=test_data$x,type="class")
  t2 <- Sys.time()
  A <- round(length(train_data$y) / 60000, 4)
  B <- round(min(1, as.numeric(t2 - t1) / 60), 4)
  C <- round(mean(predridge[,dim(predridge)[2]] != test_data$y), 4)
  
  return(list(A = A, B = B, C = C, model.name = "ridge"))
}
```

```{r load_model2}

```

### Model 3:  


```{r code_model3_development, eval = TRUE}
model_lasso <- function(train_data, test_data = test.data){
  t1 <- Sys.time()
  lasso <- glmnet(x = train_data$x, as.factor(train_data$y), alpha = 1, family = "multinomial")
  predlasso <- predict(object = lasso, newx=test_data$x,type="class")
  t2 <- Sys.time()
  A <- round(length(train_data$y) / 60000, 4)
  B <- round(min(1, as.numeric(t2 - t1) / 60), 4)
  C <- round(mean(predlasso[,dim(predlasso)[2]] != test_data$y), 4)
  
  return(list(A = A, B = B, C = C, model.name = "lasso"))
}
```

```{r load_model3}

```

### Model 4


```{r code_model4_development, eval = TRUE}

```

```{r load_model4}

```

### Model 5


```{r code_model5_development, eval = TRUE}

```

```{r load_model5}

```

### Model 6


```{r code_model6_development, eval = TRUE}

```

```{r load_model6}

```

### Model 7


```{r code_model7_development, eval = TRUE}

```

```{r load_model7}

```

### Model 8


```{r code_model8_development, eval = TRUE}

```

```{r load_model8}

```

### Model 9


```{r code_model9_development, eval = TRUE}

```

```{r load_model9}

```

### Model 10


```{r code_model10_development, eval = TRUE}

```

```{r load_model10}

```

## Scoreboard

```{r scoreboard}

```

## Discussion


## References


