---
title: "Applied Data Science:  Midterm Project"
author: ""
date: ""
output:
  prettydoc::html_pretty:
  theme: cayman
highlight: github
---

```{r setup, include=FALSE}
set.seed(72)
knitr::opts_chunk$set(echo = TRUE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55))
```

```{r libraries, echo = FALSE}
library(data.table)
library(DT)
```

```{r source_files}

```

```{r functions}

```

```{r constants}
n.values <- c(500, 1000, 2000)
iterations <- 3
```

```{r load_data}

```

```{r clean_data}

```

```{r generate_samples}

```

## Introduction


### Model 1:  


```{r code_model1_development, eval = TRUE}

```

```{r load_model1}

```

### Model 2:  


```{r code_model2_development, eval = TRUE}

```

```{r load_model2}

```

### Model 3:  


```{r code_model3_development, eval = TRUE}

```

```{r load_model3}

```

### Model 4


```{r code_model4_development, eval = TRUE}

```

```{r load_model4}

```

### Model 5


```{r code_model5_development, eval = TRUE}

```

```{r load_model5}

```

### Model 6


```{r code_model6_development, eval = TRUE}

```

```{r load_model6}

```

### Model 7


```{r code_model7_development, eval = TRUE}

```

```{r load_model7}

```

### Model 8


```{r code_model8_development, eval = TRUE}

```

```{r load_model8}

```

### Model 9


```{r code_model9_development, eval = TRUE}

```

```{r load_model9}

```

### Model 10


```{r code_model10_development, eval = TRUE}

```

```{r load_model10}

```

## Scoreboard

```{r scoreboard}

```

## Discussion


## References


