---
title: "Applied Data Science:  Midterm Project"
author: ""
date: ""
output:
  prettydoc::html_pretty:
  theme: cayman
highlight: github
---

```{r setup, include=FALSE}
set.seed(72)
knitr::opts_chunk$set(echo = TRUE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55))
```

```{r libraries, echo = FALSE}
library(data.table)
library(DT)
library(dplyr)
library(nnet)
library(class)
library(rpart)
library(FNN)
library(randomForest)
library(glmnet)
library(e1071)
library(gbm)
library(xgboost)
library(MASS)
library(klaR)
library(caret)
```

```{r source_files}

```

```{r functions}
round.numerics <- function(x, digits = 4) {
    if (is.numeric(x)) {
        x <- round(x = x, digits = digits)
    }
    return(x)
}

get.mode <- function(v) {
   unique_element <- unique(v)
   return(unique_element[which.max(tabulate(match(v, unique_element)))])
}

create.formula <- function(outcome.name, input.names, input.patterns = NA,all.data.names = NA, return.as = "character") {

  variable.names.from.patterns <- c()
  if (!is.na(input.patterns[1]) & !is.na(all.data.names[1])) {
    pattern <- paste(input.patterns, collapse = "|")
    variable.names.from.patterns <- all.data.names[grep(pattern = pattern,
    x = all.data.names)]  
  }
  
  all.input.names <- unique(c(input.names, variable.names.from.patterns))
  all.input.names <- all.input.names[all.input.names !=outcome.name]

  if (!is.na(all.data.names[1])) {
    all.input.names <- all.input.names[all.input.names %in%
    all.data.names]
   }

  input.names.delineated <- sprintf("`%s`", all.input.names)
  the.formula <- sprintf("`%s` ~ %s", outcome.name, paste(input.names.delineated,collapse = " + "))
  
  if (return.as == "formula") {
     return(as.formula(the.formula))
  }
  
  if (return.as != "formula") {
     return(the.formula)
  }
}

iteration_model <- function(learning_model,
                            train_data_list,
                            test_data = test.data) {
  
  prediction <- list()
  result <- c()
  for(i in names(train_data_list)) {
    model <- learning_model(train_data_list[[i]])
    result<- rbind(result,
                   c(model$model.name, 
                     nrow(train_data_list[[i]]), 
                     i, 
                     model$A, model$B, model$C,
                     score_model(model)))
    prediction[i] <- list(model$prediction)
  }
  dt_result <- data.table(result)
  setnames(dt_result, c("Model", "Sample Size", "Data", "A", "B", "C", "Points"))
  return(list("table" = dt_result, 
              "prediction" = prediction))
}

score_model <- function(x) {
  return(0.25 * x$A + 0.25 * x$B + 0.5 * x$C)
}

score_summary <- function(x) {
  x <- x[, .(A = round(mean(A), 4), 
             B = round(mean(B), 4),
             C = round(mean(C), 4),
             Points = round(mean(Points), 4)),
         by = c("Model", "Sample Size")]
  return(x)
}
```

```{r constants}
n.values <- c(500, 1000, 2000)
iterations <- 3
cols <- c("Sample Size", "A", "B", "C", "Points")
```

```{r load_data}
train.data <- read.csv("../Data/MNIST-fashion training set-49.csv")
test.data <- read.csv("../Data/MNIST-fashion testing set-49.csv")
```

```{r clean_data}
#normalization
train.data[,2:50] <- train.data[,2:50]/255
test.data[,2:50] <- test.data[,2:50]/255

clothes.labels <- as.vector(unique(test.data$label))
input.names <- names(test.data)[-1]
output.name <- names(test.data)[1]
train_formula <- create.formula(outcome.name = output.name, input.names = input.names)

```

```{r generate_samples}
sample_data <- function(n.values){
  temp_sample_data <- c()
  for(i in clothes.labels){
    temp_sample_data <- rbind(temp_sample_data, 
                              sample_n(train.data[train.data$label==i,], n.values/10) )
  }
  return(sample_n(temp_sample_data,n.values))
}

sample_data_list <- list()
for (i in n.values) {
  for (j in 1:iterations){
    sample_data_list[[paste( "dat", i, j, sep = "_" )]] <-  sample_data(i)
  }
}
```


## Introduction


### Model 1:  Multinomial logistic regression


```{r code_model1_development, eval = TRUE}
multinomial_logistic_regression <- function(train_data, 
                                            test_data = test.data) {
  t1 <- Sys.time()
  model <- multinom(formula = train_formula,
                    train_data,
                    trace=FALSE)
  prediction <- predict(object = model, 
                  newdata = test_data[,2:50])
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "Multinomial logistic regression", 
              "model" = model,
              "prediction" = prediction))
}
```

```{r load_model1}
temp_summary <- iteration_model(learning_model = multinomial_logistic_regression,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model1 <- temp_summary$prediction

score_board <- temp_table[,-"Data"]
```

### Model 2:  K-Nearest Neighbors


```{r code_model2_development, eval = TRUE}
k_nearest_neighbors <- function(train_data, 
                                test_data = test.data,
                                K = 5) {
  t1 <- Sys.time()
  prediction <- knn(train = train_data[,-1],
                    test = test_data[,-1],
                    cl = train_data[,1],
                    k = K)
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "5-Nearest Neighbors", 
              "model" = NA,
              "prediction" = prediction))
}
```

```{r load_model2}
temp_summary <- iteration_model(learning_model = k_nearest_neighbors,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model2 <- temp_summary$prediction

score_board <- rbind(score_board, temp_table[,-"Data"])
```

### Model 3:  Classification Tree


```{r code_model3_development, eval = TRUE}
classification_tree <- function(train_data, 
                                test_data = test.data) {
  t1 <- Sys.time()
  model <- rpart(formula = train_formula,
                 data = train_data,
                 method = "class")
  prediction <- predict(object = model,
                        newdata = test.data[,-1],
                        type = "class")
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "Classification Tree", 
              "model" = model,
              "prediction" = prediction))
}
```

```{r load_model3}
temp_summary <- iteration_model(learning_model = classification_tree,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model3 <- temp_summary$prediction

score_board <- rbind(score_board, temp_table[,-"Data"])
```

### Model 4:  Random Forest


```{r code_model4_development, eval = TRUE}
random_forest <- function(train_data, 
                          test_data = test.data) {
  t1 <- Sys.time()
  model <- randomForest(x = train_data[,-1], 
                        y = train_data[,1])
  prediction <- predict(object = model,
                        newdata = test.data[,-1])
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "Random Forest", 
              "model" = model,
              "prediction" = prediction))
}
```

```{r load_model4}
temp_summary <- iteration_model(learning_model = random_forest,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model4 <- temp_summary$prediction

score_board <- rbind(score_board, temp_table[,-"Data"])
```

### Model 5:  Ridge Regression alpha = 0


```{r code_model5_development, eval = TRUE}
ridge_regression <- function(train_data, 
                                   test_data = test.data) {
  t1 <- Sys.time()
  model <- glmnet(x = as.matrix(train_data[,-1]),
                  y = as.matrix(train_data[,1]), 
                  alpha = 0, 
                  family = "multinomial")
  prediction <- predict(object = model,
                        newx = as.matrix(test.data[,-1]),
                        type = "class")
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "Ridge Regression", 
              "model" = model,
              "prediction" = prediction))
}
```

```{r load_model5}
temp_summary <- iteration_model(learning_model = ridge_regression,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model5 <- temp_summary$prediction

score_board <- rbind(score_board, temp_table[,-"Data"])
```

### Model 6:  Lasso Regression alpha = 1


```{r code_model6_development, eval = TRUE}
lasso_regression <- function(train_data, 
                                   test_data = test.data) {
  t1 <- Sys.time()
  model <- glmnet(x = as.matrix(train_data[,-1]),
                  y = as.matrix(train_data[,1]), 
                  alpha = 1, 
                  family = "multinomial")
  prediction <- predict(object = model,
                        newx = as.matrix(test.data[,-1]),
                        type = "class")
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "Lasso Regression", 
              "model" = model,
              "prediction" = prediction))
}
```

```{r load_model6}
temp_summary <- iteration_model(learning_model = lasso_regression,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model6 <- temp_summary$prediction

score_board <- rbind(score_board, temp_table[,-"Data"])
```

### Model 7 : ElasticNet alpha = 0.5


```{r code_model7_development, eval = TRUE}
elastic_net <- function(train_data,
                        test_data = test.data) {
  t1 <- Sys.time()
  model <- glmnet(x = as.matrix(train_data[,-1]),
                  y = as.matrix(train_data[,1]), 
                  alpha = 1, 
                  family = "multinomial")
  prediction <- predict(object = model,
                        newx = as.matrix(test.data[,-1]),
                        type = "class")
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "ElasticNet", 
              "model" = model,
              "prediction" = prediction))
}
```

```{r load_model7}
temp_summary <- iteration_model(learning_model = elastic_net,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model7 <- temp_summary$prediction

score_board <- rbind(score_board, temp_table[,-"Data"])
```

### Model 8 :  Support Vector Machines


```{r code_model8_development, eval = TRUE}
support_vector_machine <- function(train_data, 
                                   test_data = test.data) {
  t1 <- Sys.time()
  model <- svm(train_data[,2:50],
               train_data[,1])
  prediction <- predict(object = model,
                        newdata = test.data[,-1])
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "Support Vector Machines", 
              "model" = model,
              "prediction" = prediction))
}
```

```{r load_model8}
temp_summary <- iteration_model(learning_model = support_vector_machine,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model8 <- temp_summary$prediction

score_board <- rbind(score_board, temp_table[,-"Data"])
```

### Model 9:  Neural Network


```{r code_model9_development, eval = TRUE}
neural_network <- function(train_data,
                           test_data = test.data) {
  t1 <- Sys.time()
  model <- nnet(label ~ .,
                data = train_data, 
                size = 2,
                rang = 0.1,
                decay = 5e-4, 
                maxit = 200,
                trace =F)
  prediction <- predict(object = model,
                        newdata = test.data[,-1],
                        type = "class")
  t2 <- Sys.time()
  
  A <-  nrow(train_data) / 60000 
  B <-  min(1, as.numeric(t2 - t1) / 60) 
  C <-  mean(prediction != test_data[,1]) 
  
  return(list("A" = A, "B" = B, "C" = C, 
              "model.name" = "Neural Network Model", 
              "model" = model,
              "prediction" = prediction))
}
```

```{r load_model9}
temp_summary <- iteration_model(learning_model = neural_network,
                                train_data_list = sample_data_list)
temp_table <- temp_summary$table
temp_table[, cols] <- temp_summary$table[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_table[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])
prediction_model9 <- temp_summary$prediction

score_board <- rbind(score_board, temp_table[,-"Data"])
```

### Model 10


```{r code_model10_development, eval = TRUE}
ensemble_model <- function(train_data_name,
                           prediction_list,
                           sample_size,
                           target = test.data[,1]) {
  t1 <- Sys.time()
  
  temp_prediction <- c()
  for (j in prediction_list) {
    temp_prediction<- cbind(temp_prediction, unlist(j[train_data_name]))
  }
  ensemble_prediction <- apply(temp_prediction, FUN = get.mode, MARGIN = 1 )
    
  t2 <- Sys.time()

  A <-  sample_size / 60000
  B <-  min(1, as.numeric(t2 - t1) / 60)
  C <-  mean(ensemble_prediction != target)

  return(list("A" = A, "B" = B, "C" = C,
              "model.name" = "Ensemble Model",
              "model" = NA,
              "prediction" = ensemble_prediction))
}
```


```{r load_model10}
prediction_list <- list("1" = prediction_model5,"2" = prediction_model6,"3" = prediction_model7)

temp_result <- c()
for (sample_name in names(sample_data_list)) {

    model <- ensemble_model(train_data_name = sample_name,
                            prediction_list = prediction_list,
                            sample_size = nrow(sample_data_list[[sample_name]]) )
    temp_result<- rbind(temp_result,
                        c(model$model.name,
                          nrow(sample_data_list[[sample_name]]),
                          sample_name,
                          model$A, model$B, model$C,
                          score_model(model)))
}

temp_dt_result <- data.table(temp_result)
setnames(temp_dt_result, c("Model", "Sample Size", "Data", "A", "B", "C", "Points"))
temp_dt_result[, cols] <- temp_dt_result[, lapply(.SD, as.numeric), .SDcols=cols]
datatable(temp_dt_result[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])

score_board <- rbind(score_board, temp_table[,-"Data"])
```

## Scoreboard

```{r scoreboard}
mean_score = aggregate(score_board[, c("A","B","C","Points")], 
                       by = list("Model" = score_board$Model, "Sample Size" = score_board$"Sample Size" ), 
                       FUN = mean)
setorderv(mean_score, cols = "Points")
dt_mean_score <- data.table(mean_score)
datatable(mean_score[, lapply(X = .SD, FUN = "round.numerics", digits = 4)])

```

## Discussion


## References


