---
title: "Applied Data Science:  Midterm Project"
author: ""
date: ""
output:
  prettydoc::html_pretty:
  theme: cayman
highlight: github
---

```{r setup, include=FALSE}
set.seed(72)
knitr::opts_chunk$set(echo = TRUE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55))
```

```{r libraries, echo = FALSE}
library(data.table)
library(DT)

library(rpart)
```

```{r source_files}

```

```{r constants}
n.values <- c(500, 1000, 2000)
iterations <- 3
# Data is 28 pixels big in width and height
img_rows <- img_cols <- 7
```


```{r load_data}
train.data <- read.csv("../Data/MNIST-fashion training set-49.csv")
test.data <- read.csv("../Data/MNIST-fashion testing set-49.csv")
```

```{r clean_data}
#' Data is transformed to matrix (because they are easier indexable) and  pixels
#' are separated from labels.
x_train <- as.matrix(train.data[, 2:dim(train.data)[2]])
y_train <- as.matrix(train.data[, 1])
# Unflattening the data.
dim(x_train) <- c(nrow(x_train), img_rows, img_cols, 1) 

# The same for test set.
x_test <- as.matrix(test.data[, 2:dim(train.data)[2]])
y_test <- as.matrix(test.data[, 1])
dim(x_test) <- c(nrow(x_test), img_rows, img_cols, 1) 

clothes.labels <-c( "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot")
```

```{r functions}
# Function to rotate matrices
rotate <- function(x) t(apply(x, 2, rev))

# Function to plot image from a matrix x
plot_image <- function(x, title = "", title.color = "black") {
  dim(x) <- c(img_rows, img_cols)
  image(rotate(rotate(x)), axes = FALSE,
        col = grey(seq(0, 1, length = 256)),
        main = list(title, col = title.color))
}

sample_data <- function(sample_size){
  dat <- c()
  for(i in c(1:10)){
    if (sample_size == 500) {
      dat <- c(dat,sample(c(1*i:6000*i), size = sample_size/10))
    }
    if (sample_size == 1000) {
      dat <- c(dat,sample(c(1*i:6000*i), size = sample_size/10))
    }
    if (sample_size == 2000) {
      dat <- c(dat,sample(c(1*i:6000*i), size = sample_size/10))
    }
  }
  return(list("x" = x_train[dat], "y" = y_train[dat]))
}
```

```{r generate_samples}
dat_500 <- sample_data(500);
dat_1000 <- sample_data(1000)
dat_2000 <- sample_data(2000)
```

```{r playground}
# We plot 16 cherry-picked images from the training set
par(mfrow=c(4, 4), mar=c(0, 0.2, 1, 0.2))
for (i in 1:16) {
  nr <- i * 10
  plot_image(x_train[nr, , , 1],
             clothes.labels[as.numeric(train.data[nr, 1] + 1)])
}
```

## Introduction


### Model 1:  


```{r code_model1_development, eval = TRUE}

```

```{r load_model1}

```

### Model 2:  


```{r code_model2_development, eval = TRUE}

```

```{r load_model2}

```

### Model 3:  


```{r code_model3_development, eval = TRUE}

```

```{r load_model3}

```

### Model 10


```{r code_model10_development, eval = TRUE}

```

```{r load_model10}

```

## Scoreboard

```{r scoreboard}

```

## Discussion


## References


